name: Package

on:
  push:
    branches:
      - master

jobs:
  package-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install pdm
          pdm install --with package
      - name: Package
        run: |
          pdm package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-graph-server_linux
          path: dist/project-graph-server*
  package-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install pdm
          pdm install --with package
      - name: Package
        run: |
          pdm package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-graph-server_windows
          path: dist/project-graph-server*
